### PR TITLE
Tangramjs bundle

### LINKED ISSUE #10: [Tangram R&D] Include Tangram.js in this bundle
To have a complete bundle without external dependencies, we have to include tangram in this bundle, this is now possible.

### PR DESCRIPTION
**Pull request by donflopez**
Fix #10

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
👍  This means we can remove [this](https://github.com/CartoDB/cartodb/pull/12182/files#diff-6cb2ca8a977e537854e3b540e80bf5f6R31), right?

🚀

**Comment by donflopez** [comment]
yes! but I have to try

**Comment by jorgesancha** [comment]
Can this be merged, then?

**Comment by donflopez** [comment]
I'll try in staging today, if everything is ok, we can remove it.

**Pull request merged**
